name: compile, build image and push image to dockerhub

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, package and upload .jar artifact
    steps:
      - uses: actions/checkout@v1
      - name: set up jvm on the VM to jdk17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
      - name: Build and package project
        run: mvn -f pom.xml clean package
      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of the target directory
        run: ls -la target
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./target/devops-tp-spring.jar
  dockerhub:
    runs-on: ubuntu-latest
    needs: release
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Authorize github to read the repo
        uses: actions/cheeckout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: maxplancher/devopsspring:latest
